### PR TITLE
Fix cron script & basic unit tests

### LINKED ISSUE #8: Scripts might be broken
After the change referenced in #7, the datasets are now located in a different repo.

This might break the cron jobs located in the scripts folder and maybe some minor changes might be necessary.

### PR DESCRIPTION
**Pull request by bill-ahmed**
Includes small fix for script that scheduled cron job. Also made it so that the script exits on the first error it encounters. Added some very simple unit tests to check all json data. Since the validations were only happening during scraping, thought it would be better to also have dedicated unit tests.

Resolves #8.

### CODE REVIEW

**Comment by bill-ahmed** [comment]
Weird...not sure why it's showing all these old commits. Only the last 3 commits actually made any changes, I might have to nuke my forked repo.

**Comment by darenliang** [comment]
Maybe you'll need to submit another pr since this pr contains code change that'll revert some recent changes.

Looking at the Files Changed section...

**Comment by bill-ahmed** [comment]
Hmm the files change only shows the stuff I recently changed. Should I re-fork the main repo and try again?

Edit: I definitely don't recall removing those blank lines for the various parsers...I think VS Code is acting up on me again.

**Comment by darenliang** [comment]
Maybe you are right.

**Comment by darenliang** [comment]
I was confused because there were empty line changes which were the lines that were changed by my autoformatter. So it looks like the pr reverted part of the formatting, but it's fine. 👍

**Pull request merged**
