### PR TITLE
Validations & Schemas for parsers

### LINKED ISSUE #4: Add schema validations for the parsers
Currently all output JSON is left un-validated. Introducing some kind of schema validation would let us catch errors with the output much earlier on, such as if UofT decided to modify their APIs or web page layouts. 

Also, adding these schema could provide a stronger back-bone for when the parsers are refactored/updated to meet new requirements (they could be incorporated into some sort of test suite later on). 

An example of a library that may do the job: https://pypi.org/project/schema/

The schema don't have to be particularly complicated, it could start with some simple validations on fields that we expect to always be present with a specific data type/format.

### PR DESCRIPTION
**Pull request by bill-ahmed**
The main addition is the schemas and validation logic for all existing parser. The validations are set to run at the _end_, and they are completed via loading the JSON dumps and checking against their respective schema.

In the event of a validation failure, the following occurs:
1. An error message is printed to console, indicating the validation did not complete successfully
2. A text file with a stack trace of the error is created, with the format  `file_name.json_DEBUG_{time_stamp}.txt`. For example: `buildings.json_DEBUG_123456.7890.txt`

The schema's have been tested against the current data sets, and appear to be passing. 

Resolves #4.

### CODE REVIEW

**Comment by bill-ahmed** [comment]
Let me know if you have any suggestions!

**Comment by bill-ahmed** [comment]
In hindsight, nuking the original data file might be problematic. Since if you want to re-run the validator, the original data would now be in a different file.

**Comment by darenliang** [comment]
Looks really good!

I think more work is needed but the current pull request will come really handy and will definitely help catch any weird messy bugs.

One thing I think would be really good is to make sure any information that we can technically backfill should be backfilled. I've taken a look at the schemas and I believe it's possible to add the date time of when the data is parsed for any `last_updated` values that are missing, it's not entirely accurate but it's better than nothing.

It could be possible to add defaults (eg. "No description") to any seemingly required fields such as `description`, but this I think is for a later time.

**Comment by darenliang** [comment]
Should this be pushed to master, or is there more work to be done?

Some changes can always come later if needed.

**Comment by bill-ahmed** [comment]
I think it's ready to merge. Although, I was wondering you could test the `exams`/`evals` parsers? I currently don't have my UofT creds setup on my testing environment so I was unable to verify that they run the validations after parsing (i'm almost certain they do, but just as a sanity check).

**Comment by darenliang** [comment]
Will do.

Currently, the exams parser is broken because layouts always change. Will definitely have to make it more robust, however, in most cases, the exams parser (and the evals parser) are rarely run as this kind of data doesn't change very often.

There are a bunch of "horrible crimes" committed in the parser code that I haven't got the time to iron out. These issues will probably be looked at as more and more of the parsers break.

**Pull request merged**
